{% set name = "fakeredis" %}
{% set version = "2.34.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4ff55606982972eecce3ab410e03d746c11fe5deda6381d913641fbd8865ea9b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - redis-py >=4.3
    - sortedcontainers >=2.4.0,<3
    - typing-extensions >=4.7,<5  # [py<311]

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - fakeredis

about:
  home: https://github.com/cunla/fakeredis-py
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: Fake implementation of redis API (redis-py) for testing purposes.
  description: |
    FakeRedis is a pure-Python implementation of the Redis key-value store.
    It enables running tests requiring redis server without an actual server.
    It provides enhanced versions of the redis-py Python bindings for Redis.
  dev_url: https://github.com/cunla/fakeredis-py
  doc_url: https://fakeredis.readthedocs.io

extra:
  recipe-maintainers:
    - viridianmelody
