{% set name = "fakeredis" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0d06a9384fb79da9f2164ce96e34eb9d4e2ea46215070805ea6fd3c174590b47

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
    - redis-py
    - six >=1.12
    - sortedcontainers
  run:
    - python >=3.6
    - redis-py
    - six >=1.12
    - sortedcontainers

test:
  imports:
    - fakeredis

about:
  home: https://github.com/jamesls/fakeredis
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: Fake implementation of redis API for testing purposes.

extra:
  recipe-maintainers:
    - Bezier89
    - pg-hbk
