travis:
  secure:
    BINSTAR_TOKEN: Y2oybu8QJ0J2P7VcHwLYX3T2Vt8rbuv5vgyQkA9Rm+31ZEDJ74Ok79Fn8Xx++3h3qN3afukDHBvP+ZrrK5k+3IWB7GeV0SlUBpU3wTD+qU94uRhJ4+2/vPVeBCy8QPRRg2KQsIMg1iECzPcCtQKLtWq+OVXmZZbUOQFYH6GBeCueVszNDsTjrSCDqc+8sBJ1EJeFSXgki3P3oaTlc2YVhEAwD6bmhzwJEQZMwU/EFOqfuvmM6+B2Psp1xWtZ9+wo7zAc1WE+mvP2V3JU6/T9+8L+ei+0Lyh4AMXuWtjEOroQkEUtZ0rJTfWKsdxOxIsErJVanGOMhJtT7smRQFzfeLaICMbGr5zH/r9A9Yt9+11cvQfh9+efE/7qpQwEbThXy3+b93pAewqCh82+lSLgRo8y3dqq2fK/Tbuc2bUhZ/ygTX838QCQIbclZH2k3Yf97H0puxJsn+MdCKLdSrtC93A3RUFWW9hF/F9e7fZqFNv1KK6kcqdefBUKHOnyR4tcsD29/SdyX4Qu+txiKEeasWmCy7leyl5PypZDIXIRopKZNXP24obHa7/qNbEHXoxRp1a/N9rdm+jBECTAecUPkbGhGeaaoe58O6XSuKYnzoERZgwsdHPbTlymjnolDWVWbYIhlrfjfhHBnaKVDlawacJSrzD3KBaq0xCqarWJd4c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
